import { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

export const swaggerConfig = (app: INestApplication) => {
  const configService = app.get(ConfigService);
  const getEnv = (key: string) => configService.get<string>(key) || '';
  const prefix = getEnv('API_PREFIX') || '';
  const projectName = getEnv('PROJECT_NAME') || 'Skygate Task';
  const authorName = getEnv('PROJECT_CONTACT_NAME') || 'Fahd Hakem';
  const authorEmail = getEnv('PROJECT_CONTACT_EMAIL') || 'fhakem75@gmail.com';
  const authorUrl =
    getEnv('PROJECT_CONTACT_URL') || 'https://www.linkedin.com/in/fahd-hakem';
  const generatedByLabel = 'Generated by Fahd';
  const brandingTitle = `${projectName} API Docs`;
  const brandingDescription = [
    `${projectName} API documentation.`,
    '',
    `Maintained and curated by ${authorName}.`,
    `Contact: [Gmail](mailto:${authorEmail}) • [LinkedIn](${authorUrl})`,
  ].join('\n');
  const contactUrl = authorUrl.startsWith('http')
    ? authorUrl
    : `https://${authorUrl}`;
  const contactEmail = authorEmail;

  const swaggerUiOptions = {
    customSiteTitle: `${brandingTitle} | ${generatedByLabel}`,
    customCss: `
      :root {
        --swagger-brand: #0f172a;
        --swagger-brand-accent: #2563eb;
        --swagger-brand-soft: #eff6ff;
        --swagger-brand-border: #dbeafe;
        --swagger-brand-text: #334155;
      }

      body {
        background:
          radial-gradient(circle at top left, rgba(37, 99, 235, 0.08), transparent 28%),
          radial-gradient(circle at top right, rgba(15, 23, 42, 0.06), transparent 24%),
          #f8fafc;
      }

      .swagger-ui .topbar {
        background: linear-gradient(135deg, var(--swagger-brand), #111827);
        border-bottom: 1px solid rgba(255, 255, 255, 0.08);
      }

      .swagger-ui .topbar .topbar-wrapper {
        max-width: 1240px;
        margin: 0 auto;
      }

      .swagger-ui .info {
        border: 1px solid var(--swagger-brand-border);
        border-radius: 18px;
        box-shadow: 0 18px 45px rgba(15, 23, 42, 0.08);
        padding: 24px;
        background: linear-gradient(180deg, #ffffff 0%, #f8fbff 100%);
      }

      .swagger-ui .info .title {
        color: var(--swagger-brand);
      }

      .swagger-ui .info .description {
        color: var(--swagger-brand-text);
        line-height: 1.7;
      }

      .swagger-ui .info .description a {
        color: var(--swagger-brand-accent);
        font-weight: 600;
      }

      .swagger-ui .scheme-container {
        border-radius: 18px;
        box-shadow: 0 12px 30px rgba(15, 23, 42, 0.05);
        border: 1px solid rgba(148, 163, 184, 0.18);
      }

      .swagger-ui .opblock {
        border-radius: 14px;
        overflow: hidden;
      }

      .swagger-ui .opblock-summary {
        padding: 12px 18px;
      }

      .swagger-ui .btn.authorize {
        border-color: var(--swagger-brand-accent);
        color: var(--swagger-brand-accent);
      }

      .swagger-ui .generated-by-banner {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 16px;
        flex-wrap: wrap;
        margin: 16px 0 24px;
        padding: 14px 18px;
        border: 1px solid var(--swagger-brand-border);
        border-radius: 16px;
        background: linear-gradient(135deg, #ffffff 0%, var(--swagger-brand-soft) 100%);
        color: var(--swagger-brand-text);
        box-shadow: 0 14px 30px rgba(15, 23, 42, 0.06);
      }

      .swagger-ui .generated-by-banner__badge {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        border-radius: 999px;
        padding: 6px 12px;
        background: var(--swagger-brand);
        color: #fff;
        font-size: 12px;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
      }

      .swagger-ui .generated-by-banner__links {
        display: flex;
        align-items: center;
        gap: 14px;
        flex-wrap: wrap;
      }

      .swagger-ui .generated-by-banner__links a {
        color: var(--swagger-brand-accent);
        font-weight: 600;
        text-decoration: none;
      }

      .swagger-ui .generated-by-banner__links a:hover {
        text-decoration: underline;
      }

      .swagger-ui .swagger-custom-footer {
        margin: 24px 0 8px;
        padding: 12px 16px;
        border-top: 1px solid rgba(148, 163, 184, 0.2);
        color: #64748b;
        font-size: 13px;
      }
    `,
    customJsStr: `
      window.addEventListener('load', function () {
        var info = document.querySelector('.swagger-ui .information-container');
        if (!info) return;

        if (document.querySelector('.swagger-ui .generated-by-banner')) return;

        var banner = document.createElement('div');
        banner.className = 'generated-by-banner';
        banner.innerHTML = [
          '<div>',
          '  <span class="generated-by-banner__badge">${generatedByLabel}</span>',
          '  <div style="margin-top:10px;font-size:16px;font-weight:700;color:#0f172a;">${authorName}</div>',
          '  <div style="margin-top:6px;font-size:14px;line-height:1.6;">Professional API reference with curated docs and clean access control.</div>',
          '</div>',
          '<div class="generated-by-banner__links">',
          '  <a href="mailto:${contactEmail}" target="_blank" rel="noreferrer noopener">Gmail</a>',
          '  <a href="${contactUrl}" target="_blank" rel="noreferrer noopener">LinkedIn</a>',
          '</div>',
        ].join('');

        info.parentNode.insertBefore(banner, info);

        var footer = document.createElement('div');
        footer.className = 'swagger-custom-footer';
        footer.innerHTML = 'Generated by <strong>${generatedByLabel}</strong> for <strong>${projectName}</strong>.';
        info.parentNode.appendChild(footer);
      });
    `,
  };

  const createDocument = (name: string, urlPath: string, scopeName: string) => {
    const builder = new DocumentBuilder()
      .setTitle(`${projectName} - ${name} API`)
      .setDescription(`${name} API documentation.\n\n${brandingDescription}`)
      .setVersion('1.0')
      .setContact(authorName, contactUrl, contactEmail)
      .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'ACCESS Token')
      .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'REFRESH Token')
      .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'VERIFY Token')
      .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'PASSWORD_RESET Token')
      .addGlobalParameters({
        in: 'header',
        required: false,
        name: 'Locale',
        schema: { example: 'en' },
      })
      .addGlobalParameters({
        in: 'header',
        required: false,
        name: 'isLocalized',
        schema: { type: 'boolean', default: false },
      });

    const config = builder.build();
    const baseDocument = SwaggerModule.createDocument(app, config);

    const filteredDocument = {
      ...baseDocument,
      paths: Object.keys(baseDocument.paths).reduce((acc, key) => {
        const pathItem = baseDocument.paths[key];
        const newPathItem: Record<string, unknown> = {};
        let hasMethods = false;

        ['get', 'post', 'put', 'delete', 'patch', 'options', 'head'].forEach(
          (method) => {
            if (pathItem[method]) {
              const operation = pathItem[method];
              const hasScope = operation[`x-scope-${scopeName}`];

              if (hasScope) {
                newPathItem[method] = operation;
                hasMethods = true;
              }
            }
          },
        );

        if (hasMethods) {
          acc[key] = newPathItem;
        }
        return acc;
      }, {}),
    };

    SwaggerModule.setup(`${prefix}/docs/${urlPath}`, app, filteredDocument, {
      ...swaggerUiOptions,
      customSiteTitle: `${projectName} | ${name} API`,
      swaggerOptions: {
        docExpansion: 'none',
        filter: true,
      },
    });
  };

  const mainBuilder = new DocumentBuilder()
    .setTitle(`${projectName} API`)
    .setDescription(brandingDescription)
    .setVersion('1.0')
    .setContact(authorName, contactUrl, contactEmail)
    .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'ACCESS Token')
    .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'REFRESH Token')
    .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'VERIFY Token')
    .addBearerAuth({ type: 'http', scheme: 'bearer' }, 'PASSWORD_RESET Token')
    .addGlobalParameters({
      in: 'header',
      required: false,
      name: 'Locale',
      schema: { example: 'en' },
    })
    .addGlobalParameters({
      in: 'header',
      required: false,
      name: 'isLocalized',
      schema: { type: 'boolean', default: false },
    });

  const mainConfig = mainBuilder.build();
  const mainDoc = SwaggerModule.createDocument(app, mainConfig);
  SwaggerModule.setup(`${prefix}/docs`, app, mainDoc, swaggerUiOptions);

  createDocument('Admin', 'admin', 'admin');
  createDocument('Customer', 'customer', 'customer');
  createDocument('Host', 'host', 'host');
};
